"use client";
import { useEffect, useState } from "react";
const roles = [
  { period: "2025 — 2026", company: "Oracle", role: "Engineering Manager · AI Data Platform", summary: "Led the connectivity layer that brings enterprise data into Oracle 23ai—turning a complex integration surface into a reliable, compliant platform.", wins: ["14 production data connectors", "70% lower read latency", "85%+ test coverage", "FIPS 140-3 certification"], tone: "orange" },
  { period: "2021 — 2024", company: "Fynd · Reliance Industries", role: "Engineering Manager · Platform & Integrations", summary: "Built the engineering organisation behind one of Reliance Retail’s largest B2B commerce migrations, connecting product, inventory, and orders at national scale.", wins: ["Team scaled 5 → 20", "5M+ active merchants", "3M+ SKUs", "Zero-downtime migration"], tone: "green" },
  { period: "2010 — 2021", company: "CDAC · Government of India", role: "SDE → Architect → Engineering Manager", summary: "Grew from individual contributor to engineering leader, shipping public digital infrastructure spanning mobility, health, water, IoT, and education.", wins: ["1.2M+ app downloads", "8,000 IoT sensors", "₹300 Cr+ portfolio", "10+ public products"], tone: "blue" },
];
const products = [
  { name: "Oracle AI Data Platform", href: "https://www.oracle.com/ai-data-platform/", meta: "Enterprise AI · Oracle", description: "A secure connectivity layer that turns fragmented enterprise data into an AI-ready foundation." },
  { name: "Reliance B2B Commerce", href: "https://www.fynd.com/", meta: "Commerce at scale · Fynd", description: "The platform backbone behind nationwide B2B journeys for millions of merchants and millions of SKUs." },
  { name: "Namma Metro", href: "https://play.google.com/store/apps/details?id=com.aum.nammametro", meta: "Public mobility · BMRCL", description: "Bengaluru’s official metro companion—putting routes, fares, and travel information in 1.2M+ pockets." },
  { name: "Smart Water Network", href: "https://www.cdac.in/", meta: "Urban infrastructure · C-DAC", description: "An IoT data platform that made 8,000 sensors across 40 locations observable and actionable." },
];
const projects = [
  { name: "Job Tracker", href: "https://github.com/utkarshmankad/job-tracker", tech: "Python · React", description: "A private, local-first command centre that turns job emails into a live application pipeline." },
  { name: "JD Fit Checker", href: "https://jd-fit-checker.vercel.app", tech: "Next.js · AI", description: "An AI screening copilot that scores roles, exposes gaps, and helps job seekers focus their search." },
  { name: "ReportAPI", href: "https://reportapi.vercel.app", tech: "TypeScript · Next.js", description: "A modern web product for creating and sharing useful reports without the usual reporting friction." },
  { name: "Chandy–Misra–Haas", href: "https://github.com/utkarshmankad/Chandy-Misra-Haas-AND-model", tech: "C++ · Distributed systems", description: "A hands-on implementation of probe-based deadlock detection for distributed AND models." },
  { name: "Inverted Index Search", href: "https://github.com/utkarshmankad/inverted-index-boolean-search", tech: "Python · NLP", description: "A compact search engine that indexes documents and resolves Boolean queries with NLTK." },
  { name: "Suzuki–Kasami Broadcast", href: "https://github.com/utkarshmankad/suzuki-kasami-broadcast-algorithm", tech: "C++ · Algorithms", description: "A token-based simulation that makes distributed mutual exclusion tangible and testable." },
];
const capabilities = ["Engineering leadership", "AI & data platforms", "Distributed systems", "Organisation design", "Cloud-native SaaS", "Reliability & SRE", "Executive alignment", "Talent development"];
export default function Home() {
  const [dark, setDark] = useState(false);
  useEffect(() => { const saved = localStorage.getItem("theme"); queueMicrotask(() => setDark(saved ? saved === "dark" : window.matchMedia("(prefers-color-scheme: dark)").matches)); }, []);
  useEffect(() => { document.documentElement.dataset.theme = dark ? "dark" : "light"; localStorage.setItem("theme", dark ? "dark" : "light"); }, [dark]);
  return <main>
    <nav className="nav" aria-label="Primary navigation"><a className="brand" href="#top">UM<span>.</span></a><div className="navLinks"><a href="#work">Work</a><a href="#products">Products</a><a href="#projects">Projects</a><a href="#about">About</a><a href="#contact">Contact</a><button className="themeButton" onClick={() => setDark(!dark)} aria-label={`Switch to ${dark ? "light" : "dark"} theme`}><span aria-hidden>{dark ? "☀" : "◐"}</span> {dark ? "Light" : "Dark"}</button></div></nav>
    <section className="hero" id="top"><div className="eyebrow"><span className="statusDot" /> Bengaluru, India · Open to conversations</div><h1>I build teams that build<br /><em>systems that matter.</em></h1><p className="heroCopy">Engineering leader with 16 years across enterprise AI, high-scale commerce, and public digital infrastructure.</p><div className="heroActions"><a className="primaryButton" href="#work">Explore my work <span>↘</span></a><a className="textLink" href="mailto:utkarsh.mankad@gmail.com">Start a conversation</a></div></section>
    <section className="metrics" aria-label="Career highlights"><div><strong>16</strong><span>Years in technology</span></div><div><strong>20</strong><span>Engineers led</span></div><div><strong>4</strong><span>Teams built</span></div><div><strong>5M+</strong><span>Merchants served</span></div></section>
    <section className="section work" id="work"><header className="sectionHead"><p>01 / Selected impact</p><h2>From research labs<br />to enterprise AI.</h2></header><div className="timeline">{roles.map((role, index) => <article className="role" key={role.company}><div className="roleIndex">0{index + 1}</div><div className="roleMain"><span className="period">{role.period}</span><h3>{role.company}</h3><h4>{role.role}</h4><p>{role.summary}</p><ul className={role.tone}>{role.wins.map(win => <li key={win}>{win}</li>)}</ul></div></article>)}</div></section>
    <section className="section showcase" id="products"><header className="sectionHead compact"><p>02 / Products shipped</p><h2>Platforms built for<br />real-world scale.</h2></header><div className="showcaseGrid">{products.map((product, index) => <article className="showcaseCard" key={product.name}><span className="cardNumber">{String(index + 1).padStart(2, "0")}</span><p>{product.meta}</p><h3><a href={product.href} target="_blank" rel="noreferrer">{product.name} ↗</a></h3><p className="cardDescription">{product.description}</p></article>)}</div></section>
    <section className="section showcase projects" id="projects"><header className="sectionHead compact"><p>03 / Open source & experiments</p><h2>Ideas made<br />executable.</h2></header><div className="showcaseGrid projectGrid">{projects.map((project, index) => <article className="showcaseCard projectCard" key={project.name}><span className="cardNumber">{String(index + 1).padStart(2, "0")}</span><p>{project.tech}</p><h3><a href={project.href} target="_blank" rel="noreferrer">{project.name} ↗</a></h3><p className="cardDescription">{project.description}</p></article>)}</div></section>
    <section className="section about" id="about"><div className="portraitWrap"><img src="/utkarsh.jpg" alt="Utkarsh Mankad" /><span>Builder · Leader · Learner</span></div><div className="aboutCopy"><p className="kicker">04 / How I lead</p><h2>Clarity over noise.<br /><em>Outcomes over activity.</em></h2><p className="lead">I’m at my best where technology, people, and purpose meet.</p><p>My path from hands-on engineer to organisational leader taught me that durable systems and durable teams are built the same way: with clear interfaces, honest feedback, calm ownership, and room to grow.</p><blockquote>“Turn ambiguity into direction—and leave every system stronger than you found it.”</blockquote></div></section>
    <section className="section expertise"><header className="sectionHead compact"><p>05 / What I bring</p><h2>Leadership with<br />technical depth.</h2></header><div className="capabilities">{capabilities.map((capability, index) => <div key={capability}><span>{String(index + 1).padStart(2, "0")}</span>{capability}</div>)}</div><p className="stack">Java · Python · Scala · Spark · TypeScript · React · Node.js · Kafka · MongoDB · PostgreSQL · Kubernetes · AWS · GCP · OCI · RAG · LangGraph</p></section>
    <section className="section writing" id="writing"><header className="sectionHead compact"><p>06 / Ideas in practice</p><h2>I write to make<br />complexity useful.</h2></header><div className="articles"><a href="https://www.linkedin.com/in/utkarsh-mankad/" target="_blank" rel="noreferrer"><span>Engineering practice · 2025</span><h3>Automated Canary Deployments: Strategies for Safer Software Releases</h3><b>Read on LinkedIn ↗</b></a><a href="https://www.linkedin.com/in/utkarsh-mankad/" target="_blank" rel="noreferrer"><span>Data platforms · 2025</span><h3>Unlocking the Power of Big Data: Understanding Spark Connector Architecture</h3><b>Read on LinkedIn ↗</b></a></div></section>
    <footer id="contact"><p className="kicker">07 / Let’s connect</p><h2>Building something<br /><em>that should matter?</em></h2><a className="email" href="mailto:utkarsh.mankad@gmail.com">utkarsh.mankad@gmail.com ↗</a><div className="footerBottom"><span>© {new Date().getFullYear()} Utkarsh Mankad</span><div><a href="https://github.com/utkarshmankad" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/utkarsh-mankad/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div><a href="#top">Back to top ↑</a></div></footer>
  </main>;
}
