"use client";
import { useEffect,useState } from "react";
const roles=[
 {period:"2025 — 2026",company:"Oracle",role:"Engineering Manager · AI Data Platform",summary:"Led the connectivity layer that brings enterprise data into Oracle 23ai—turning a complex integration surface into a reliable, compliant platform.",wins:["14 production data connectors","70% lower read latency","85%+ test coverage","FIPS 140-3 certification"],tone:"orange"},
 {period:"2021 — 2024",company:"Fynd · Reliance Industries",role:"Engineering Manager · Platform & Integrations",summary:"Built the engineering organisation behind one of Reliance Retail’s largest B2B commerce migrations, connecting product, inventory, and orders at national scale.",wins:["Team scaled 5 → 20","5M+ active merchants","3M+ SKUs","Zero-downtime migration"],tone:"green"},
 {period:"2010 — 2021",company:"CDAC · Government of India",role:"SDE → Architect → Engineering Manager",summary:"Grew from individual contributor to engineering leader, shipping public digital infrastructure spanning mobility, health, water, IoT, and education.",wins:["1.2M+ app downloads","8,000 IoT sensors","₹300 Cr+ portfolio","10+ public products"],tone:"blue"}
];
const capabilities=["Engineering leadership","AI & data platforms","Distributed systems","Organisation design","Cloud-native SaaS","Reliability & SRE","Executive alignment","Talent development"];
export default function Home(){
 const [dark,setDark]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem("theme");queueMicrotask(()=>setDark(saved?saved==="dark":window.matchMedia("(prefers-color-scheme: dark)").matches))},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("theme",dark?"dark":"light")},[dark]);
 return <main>
  <nav className="nav" aria-label="Primary navigation"><a className="brand" href="#top">UM<span>.</span></a><div className="navLinks"><a href="#work">Work</a><a href="#about">About</a><a href="#writing">Writing</a><a href="#contact">Contact</a><button className="themeButton" onClick={()=>setDark(!dark)} aria-label={`Switch to ${dark?"light":"dark"} theme`}><span aria-hidden>{dark?"☀":"◐"}</span> {dark?"Light":"Dark"}</button></div></nav>
  <section className="hero" id="top"><div className="eyebrow"><span className="statusDot"/> Bengaluru, India · Open to conversations</div><h1>I build teams that build<br/><em>systems that matter.</em></h1><p className="heroCopy">Engineering leader with 16 years across enterprise AI, high-scale commerce, and public digital infrastructure.</p><div className="heroActions"><a className="primaryButton" href="#work">Explore my work <span>↘</span></a><a className="textLink" href="mailto:utkarsh.mankad@gmail.com">Start a conversation</a></div></section>
  <section className="metrics" aria-label="Career highlights"><div><strong>16</strong><span>Years in technology</span></div><div><strong>20</strong><span>Engineers led</span></div><div><strong>70%</strong><span>Latency reduced</span></div><div><strong>5M+</strong><span>Merchants served</span></div></section>
  <section className="section work" id="work"><header className="sectionHead"><p>01 / Selected impact</p><h2>From research labs<br/>to enterprise AI.</h2></header><div className="timeline">{roles.map((r,i)=><article className="role" key={r.company}><div className="roleIndex">0{i+1}</div><div className="roleMain"><span className="period">{r.period}</span><h3>{r.company}</h3><h4>{r.role}</h4><p>{r.summary}</p><ul className={r.tone}>{r.wins.map(w=><li key={w}>{w}</li>)}</ul></div></article>)}</div></section>
  <section className="section about" id="about"><div className="portraitWrap"><img src="/utkarsh.jpg" alt="Utkarsh Mankad"/><span>Builder · Leader · Learner</span></div><div className="aboutCopy"><p className="kicker">02 / How I lead</p><h2>Clarity over noise.<br/><em>Outcomes over activity.</em></h2><p className="lead">I’m at my best where technology, people, and purpose meet.</p><p>My path from hands-on engineer to organisational leader taught me that durable systems and durable teams are built the same way: with clear interfaces, honest feedback, calm ownership, and room to grow.</p><blockquote>“Turn ambiguity into direction—and leave every system stronger than you found it.”</blockquote></div></section>
  <section className="section expertise"><header className="sectionHead compact"><p>03 / What I bring</p><h2>Leadership with<br/>technical depth.</h2></header><div className="capabilities">{capabilities.map((c,i)=><div key={c}><span>{String(i+1).padStart(2,"0")}</span>{c}</div>)}</div><p className="stack">Java · Python · Scala · Spark · TypeScript · React · Node.js · Kafka · MongoDB · PostgreSQL · Kubernetes · AWS · GCP · OCI · RAG · LangGraph</p></section>
  <section className="section writing" id="writing"><header className="sectionHead compact"><p>04 / Ideas in practice</p><h2>I write to make<br/>complexity useful.</h2></header><div className="articles"><a href="https://www.linkedin.com/in/utkarsh-mankad/" target="_blank" rel="noreferrer"><span>Engineering practice · 2025</span><h3>Automated Canary Deployments: Strategies for Safer Software Releases</h3><b>Read on LinkedIn ↗</b></a><a href="https://www.linkedin.com/in/utkarsh-mankad/" target="_blank" rel="noreferrer"><span>Data platforms · 2025</span><h3>Unlocking the Power of Big Data: Understanding Spark Connector Architecture</h3><b>Read on LinkedIn ↗</b></a></div></section>
  <footer id="contact"><p className="kicker">05 / Let’s connect</p><h2>Building something<br/><em>that should matter?</em></h2><a className="email" href="mailto:utkarsh.mankad@gmail.com">utkarsh.mankad@gmail.com ↗</a><div className="footerBottom"><span>© {new Date().getFullYear()} Utkarsh Mankad</span><div><a href="https://github.com/utkarshmankad" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/utkarsh-mankad/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div><a href="#top">Back to top ↑</a></div></footer>
 </main>
}
